spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ifeanyichukwuOtiwa-sports/config-server
          default-label: develop
          timeout: 5
          clone-on-start: true
          force-pull: true


server:
  port: 9000
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 2s
    keep-alive-timeout: 15s
