apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service

spec:
  selector:
    app: config-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000